# .github/workflows/forms-automation.yml
name: Daily Forms Report

on:
  schedule:
    # Run daily at 9:00 AM UTC (adjust for your timezone)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  send-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run forms automation
      env:
        DATA_SOURCE: ${{ secrets.DATA_SOURCE }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        USE_TLS: ${{ secrets.USE_TLS }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
      run: python simple_forms_automation.py
      
    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: automation-logs
        path: |
          *.log
          *.png
          *.csv
